package com.wanjaniko.authorblog

import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat


import androidx.recyclerview.widget.LinearLayoutManager
import com.wanjaniko.authorblog.databinding.ActivityMainBinding
class MainActivity : AppCompatActivity() {
    lateinit var binding: ActivityMainBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.rvArticles.layoutManager= LinearLayoutManager(this)
        displayArticles()
    }
    fun displayArticles(){
        val article1 = Author("Jane Eyre","", "Education", "Published on: 13th Nov 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article2 = Author("Paulo Coelho","", "Health", "Published on: 5th Dec 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article3 = Author("Jane Austine","", "Business", "Published on: 4th June2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article4 = Author("Charles Dickens","", "Sports", "Published on: 8th July 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article5 = Author("Emily Bronte","", "Religious", "Published on: 19th Jan 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article6 = Author("Levley Jane","", "Technology", "Published on: 12 Sept 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val article7 = Author("Starlet Mwiki","", "Communication", "Published on: 19th Oct 2024", "Paulo Coelho is one of the most well-known authors in literary history. And much like his creative works, his personal story is full of twists and turns. When Paulo Coelho told his parents he aspired to be a writer, they thought he was physically insane. Paulo Coelho was born on August 24, 1947, and raised in Rio de Janeiro, Brazil. He is most known for using complex symbolism to depict the journeys of his characters, who are typically motivated by spiritual beliefs. Paulo Coelho revisits ancient legends and remote customs in order to evoke themes of love, the quest for self-knowledge, and the genesis of thought. He discusses independence and solitude while considering the future of humanity in his search for safety, love, and spirituality. He is the author of novels that have been translated into 81 different languages and 170 different countries, giving him geographical independence. Coelho blatantly distinguishes himself from other Brazilian authors, with over 210 million copies sold.","View more")
        val articlesList = listOf(article1,article2,article3,article4,article5,article6,article7)
        val articleAdapter = ArticleAdapter(articlesList)
        binding.rvArticles.adapter = articleAdapter
    }
}